#!/bin/bash
# openoffice.org headless server script
#
# Author: Vic Vijayakumar
# Modified by Federico Ch. Tomasczik
# Vastly Modified by Gervais de Montbrun -> February 2014
# Slightly changed by Luke Taylor -> Jan.2016
## Tested with LibreOffice 3.5 on Ubuntu 12.04.3 LTS
## Ubuntu has dropped openoffice.org-headless package
#
# it's a service!
### BEGIN INIT INFO
# chkconfig: 2345 80 30
# processname: openoffice
# Provides: openoffice headless
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start openoffice-headless at boot.
# Description: headless openoffice server script
### END INIT INFO

OOo_HOME=/usr/bin
SOFFICE_PATH=$OOo_HOME/soffice
PID_SEARCH="pgrep -nf $SOFFICE_PATH"

set -e

case "$1" in
  start)
    if [ `$PID_SEARCH` ]; then
     echo "OpenOffice headless server has already started."
    else
      echo "Starting OpenOffice headless server"
      /bin/su - openoffice -c "$SOFFICE_PATH --headless --nologo --nofirststartwizard --accept=\"socket,host=127.0.0.1,port=8100;urp\"" & > /dev/null 2>&1
    fi
  ;;

  stop)
    if [ `$PID_SEARCH` ]; then
      echo "Stopping OpenOffice headless server."
      killall -9 soffice.bin
    else
      echo "Openoffice headless server is not running."
    fi
  ;;

  status)
    if [ `$PID_SEARCH` ]; then
      echo "OpenOffice headless is running"
      exit 0
    else
      echo "OpenOffice headless is not currently running, you can start it with $0 start"
      exit 1
    fi
  ;;

restart) $0 stop ; $0 start ;;
status) status ;;

*)
  echo "Usage: $0 {start|stop|restart|status}"
  exit 1
esac
exit 0
