#!/bin/bash
# openoffice.org headless server script
#
# chkconfig: 2345 80 30
# description: headless openoffice server script
# processname: openoffice
#
# Author: Vic Vijayakumar
# Modified by Federico Ch. Tomasczik
# Modified by Gervais de Montbrun -> October 9, 2013
#  Tested with LibreOffice 3.5 on Ubuntu 12.04.3 LTS
## Ubuntu has dropped openoffice.org-headless package

OOo_HOME=/usr/bin
SOFFICE_PATH=$OOo_HOME/soffice
PIDFILE=/var/run/openoffice-server.pid

set -e

case "$1" in
  start)
    if [ -f $PIDFILE ]; then
     echo "OpenOffice headless server has already started."
     sleep 5
     exit
    fi
    echo "Starting OpenOffice headless server"
    $SOFFICE_PATH --headless --nologo --nofirststartwizard --accept="socket,host=127.0.0.1,port=8100;urp" & > /dev/null 2>&1
    touch $PIDFILE
;;

  stop)
    if [ -f $PIDFILE ]; then
     echo "Stopping OpenOffice headless server."
     killall -9 soffice.bin
     rm -f $PIDFILE
     exit
    fi
    echo "Openoffice headless server is not running."
    exit
;;

status)
 PID=`$PID_SEARCH`

  if [ -f $PIDFILE ]; then
    echo "There's a pid file there so LibreOffice *should* be running"
  else
    echo "LibreOffice is not currently running, you can start it with $0 start"
  fi
;;

restart) $0 stop ; $0 start ;;
status) status ;;

*)
  echo "Usage: $0 {start|stop|restart|status}"
  exit 1
esac
exit 0
